##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [41]:
import numpy as np
n = np.array([15,45,47,5,9,63])
type(n)
n.dtype

dtype('int32')

In [18]:
np.array([15,45,47,5,9,63])

array([15, 45, 47,  5,  9, 63])

In [20]:
array = np.array([15,45,47,5,9,63])
print(array.ndim)
print(array.size)

1
6


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [45]:
import numpy as np
array = ([[1,2,6,7],[4,3,9,5]])
array3 = ([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])


In [51]:
k = np.array([[1,2,6,7],[4,3,9,5]])
m = np.array([[[7,5,14],[21,8,11]],[[8,6,20],[14,3,9]]])

In [55]:
print(k.size)

8


In [56]:
print(m.size)

12


In [54]:
k.dtype

dtype('int32')

In [53]:

m.dtype

dtype('int32')

In [57]:
np.shape(k)

(2, 4)

In [58]:
np.shape(m)

(2, 2, 3)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [59]:
k

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [60]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
k[0,1]

2

In [61]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
k[0,3]

7

In [62]:
m

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [63]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
m[1,1,2]

9

In [64]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
m[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [65]:
k

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [69]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
k[0,1:3]

array([2, 6])

In [70]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
k[1,1:4]

array([3, 9, 5])

In [71]:
m

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [72]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
m[0,1,0:3]

array([21,  8, 11])

In [73]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
m[1,0,1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [82]:
import numpy as np
y = np.array([[0,0,0],[0,0,1],[0,1,0],[1,0,0],[1,1,1]])

In [83]:
np.concatenate([y,y],axis=1)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 1]])